export const NOVA_SOL_ANCHOR =
  "Adult female anime character, warm golden-brown caramel-bronze dark skin, softly heart-shaped face, delicate features, thin arched brows, large expressive warm amber-gold eyes, full glossy lips, soft confident smile. Shoulder-length dark brown hair with copper-gold warmth and soft loose waves with volume. Gold hoop earrings, gold bangle bracelets on both wrists. Orange cropped bomber jacket worn open, white structured bustier top with black strap detail, high-waisted black fitted shorts, slim black belt with gold buckle. Confident relaxed pose, one hand near collarbone, other hand on hip. Warm golden-hour rim lighting on skin and hair. Polished premium anime character illustration, clean cel-shaded linework, high detail, rich warm color harmony.";

export const VIEWPOINTS = [
  "wide establishing shot",
  "low angle looking up",
  "bird's eye overhead",
  "over-the-shoulder",
  "isometric perspective",
  "eye-level street view",
  "dramatic worm's eye",
  "medium distance with depth",
];

export const TIMES_OF_DAY = [
  "golden hour",
  "blue hour",
  "midnight",
  "midday",
  "pre-dawn",
  "late afternoon",
  "dusk",
  "early morning",
];

export const SEASONS = [
  "summer",
  "autumn",
  "winter",
  "spring",
  "late spring",
  "early winter",
  "midsummer",
  "rainy season",
];

export const COLOR_PALETTES = [
  "warm amber and deep brown",
  "cool teal and slate gray",
  "muted sage and cream",
  "rich violet and gold",
  "monochrome blue-gray",
  "warm terracotta and rust",
  "neon magenta and deep black",
  "soft peach and dusty rose",
  "synthwave purple and cyan",
  "earthy olive and bronze",
];

export const COMPOSITIONS = [
  "centered symmetry",
  "rule of thirds",
  "diagonal flow left to right",
  "layered depth planes",
  "leading lines to horizon",
  "frame within a frame",
  "asymmetric weight right",
  "S-curve depth",
];

export const TEXTURES = [
  "matte concrete",
  "wet chrome",
  "frosted glass",
  "worn denim",
  "brushed metal",
  "polished marble",
  "rough brick",
  "soft velvet",
  "aged wood",
  "translucent resin",
];

export const DEPTHS = [
  "shallow focus with foreground blur",
  "deep infinite focus",
  "rack focus on midground",
  "soft bokeh background",
  "tack-sharp foreground",
  "medium depth of field",
];

export const SOUND_REFS = [
  "lo-fi hip hop beat",
  "synthwave electro pulse",
  "ambient drone",
  "Afrobeat rhythm",
  "festival EDM drop",
  "jazz piano late night",
  "city rain ambience",
  "vaporwave tape hiss",
  "deep house groove",
  "ethereal vocal pad",
];

export const FOREGROUNDS = {
  "Setup Vibe": [
    "desk surface with scattered papers",
    "keyboard edge in frame",
    "coffee mug rim close-up",
    "headphone cable draped",
    "open notebook corner",
    "plant leaves framing edge",
    "monitor bezel close",
    "controller resting on surface",
  ],
  "Sunset Pulse": [
    "iron railing detail",
    "wet stone ledge",
    "grass blades close",
    "cracked asphalt edge",
    "wooden fence post",
    "bench armrest",
    "overgrown wall top",
    "concrete barrier",
  ],
  "Neon Deck": [
    "wet pavement reflection",
    "neon-lit puddle",
    "chain-link fence mesh",
    "dumpster corner",
    "rain-slicked curb",
    "gravel and broken glass",
    "cable coils",
    "chain railing",
  ],
  "Fantasy Tech": [
    "overgrown tech panel edge",
    "crystal shard formation",
    "rune-etched console rim",
    "floating debris fragment",
    "bioluminescent moss",
    "corroded metal grating",
    "alien root structure",
    "glowing conduit pipe",
  ],
  SynthWave: [
    "chrome railing close-up",
    "cassette tape edge",
    "retro joystick corner",
    "glowing grid line",
    "VHS scan-line texture",
    "neon tube refraction",
    "chrome bumper detail",
    "rubber-sealed hatch rim",
  ],
};

export const LANES = {
  "Setup Vibe": {
    tag: "SETUP VIBE",
    color: "#38bdf8",
    dim: "#0e2a3a",
    glow: "0 0 40px rgba(56,189,248,0.2)",
    environments: [
      "gaming battlestation",
      "dual-monitor creator studio",
      "lo-fi producer bedroom",
      "RGB-lit streaming cave",
      "late-night coding den",
      "minimalist desk with city view",
      "aesthetic creator loft",
      "vinyl corner with soft lamp",
    ],
    moods: [
      "focused midnight grind",
      "chill creative flow",
      "neon-lit calm",
      "peak performance energy",
      "late-night hustle",
      "productive serenity",
    ],
    lighting: [
      "RGB gradient wash",
      "monitor blue-glow backlight",
      "soft desk lamp warmth",
      "neon strip backlighting",
      "city-window ambient",
      "warm practical desk light",
    ],
    weather: [
      "rain streaking the window",
      "dry still night",
      "distant city haze",
      "soft condensation on glass",
      "cool clear evening",
      "light fog beyond the glass",
    ],
    details: [
      "coffee steam rising",
      "lo-fi playlist on screen",
      "action figures on shelf",
      "cable-managed clean setup",
      "plant beside monitor",
      "headphones resting on desk",
      "cat curled on chair",
      "journal open beside keyboard",
    ],
    style: [
      "Makoto Shinkai cinematic 2D anime background",
      "lofi anime background illustration",
      "CoMix Wave Films atmospheric painterly style",
      "Korean webtoon background art",
      "premium 2D anime environment art",
    ],
    ratios: ["16:9", "4:5", "2:3"],
    neg: "photorealistic, 3D render, CGI, characters in foreground, blurry, low quality, watermark, text, logo, signature, drop shadows, flat lighting, ground plane, oversaturated, noisy, muddy colors, cluttered composition",
    etsyKeywords: [
      "gaming room wall art",
      "creator room decor",
      "lo-fi room print",
      "desk setup poster",
      "gaming desk art print",
      "aesthetic room decor",
      "streamer room wall art",
      "producer desk print",
      "gaming setup printable",
      "lofi bedroom art",
    ],
    etsyTitleBase: [
      "Lo-Fi Gaming Room",
      "Creator Desk",
      "Aesthetic Studio Setup",
      "Neon Gaming Lair",
      "Producer Room",
    ],
    rbKeywords: [
      "gaming room",
      "lofi desk",
      "creator setup",
      "neon gaming",
      "aesthetic room",
      "producer workspace",
      "streamer cave",
      "desk vibes",
    ],
    rbProducts: [
      "poster",
      "art print",
      "sticker",
      "notebook",
      "phone case",
      "laptop sleeve",
    ],
  },
  "Sunset Pulse": {
    tag: "SUNSET PULSE",
    color: "#fb923c",
    dim: "#2a1200",
    glow: "0 0 40px rgba(251,146,60,0.2)",
    environments: [
      "rooftop terrace overlooking the city",
      "coastal boardwalk at dusk",
      "open field horizon",
      "mountain overlook",
      "elevated train platform",
      "ocean pier",
      "desert highway",
      "cherry blossom avenue",
    ],
    moods: [
      "golden nostalgic warmth",
      "bittersweet dusk calm",
      "slow-burning wonder",
      "last-light serenity",
      "warm reverie",
      "euphoric golden hour",
    ],
    lighting: [
      "warm tangerine backlight",
      "split horizon amber glow",
      "long-shadow golden hour",
      "crimson cloud scatter",
      "soft salmon haze",
      "peach-gold diffusion",
    ],
    weather: [
      "clear sky with warm haze",
      "thin cirrus clouds catching fire",
      "calm windless dusk",
      "golden mist on the horizon",
      "last rays through clouds",
      "gentle warm breeze in the trees",
    ],
    details: [
      "birds silhouetted against sky",
      "power lines in foreground",
      "distant city glow on horizon",
      "lens flare streak",
      "cherry blossoms catching final light",
      "slow traffic light trails",
      "a lone bench",
      "telephone poles receding",
    ],
    style: [
      "Makoto Shinkai cinematic 2D anime background",
      "CoMix Wave Films painterly atmosphere",
      "premium anime sunset background art",
      "Studio Ghibli-influenced warm painterly 2D",
    ],
    ratios: ["16:9", "4:5", "2:3", "1:1"],
    neg: "photorealistic, 3D render, CGI, characters in foreground, blurry, low quality, watermark, text, logo, signature, drop shadows, flat lighting, ground plane, cold colors, desaturated, noisy, muddy, overexposed",
    etsyKeywords: [
      "synthwave wall art",
      "sunset poster print",
      "neon city wall art",
      "golden hour print",
      "anime sunset poster",
      "music room decor",
      "city skyline art print",
      "warm wall art printable",
      "sunset digital download",
      "aesthetic sunset art",
    ],
    etsyTitleBase: [
      "Golden Hour Cityscape",
      "Synthwave Sunset",
      "Warm City Glow",
      "Anime Dusk Horizon",
      "Neon Sunset Skyline",
    ],
    rbKeywords: [
      "sunset art",
      "golden hour",
      "synthwave sunset",
      "warm skyline",
      "anime sunset",
      "city at dusk",
      "neon horizon",
      "sunset vibes",
    ],
    rbProducts: [
      "poster",
      "art print",
      "canvas print",
      "sticker",
      "phone case",
      "tapestry",
    ],
  },
  "Neon Deck": {
    tag: "NEON DECK",
    color: "#e879f9",
    dim: "#1e0a2a",
    glow: "0 0 40px rgba(232,121,249,0.2)",
    environments: [
      "rain-slicked neon street",
      "elevated monorail platform at night",
      "retro arcade interior",
      "underground club entrance",
      "cyberpunk market alley",
      "rooftop above the city grid",
      "retrofuture highway overpass",
      "vinyl record shop interior at night",
    ],
    moods: [
      "electric isolation",
      "neon fever dream",
      "synthwave nostalgia",
      "retrowave euphoria",
      "glitch-soaked calm",
      "late-night magnetic energy",
    ],
    lighting: [
      "magenta-cyan split neon wash",
      "rain-reflected neon bloom",
      "holographic projection glow",
      "purple smog ambient",
      "flickering signage contrast",
      "violet-teal neon layering",
    ],
    weather: [
      "heavy rain and wet streets",
      "light drizzle with neon halos",
      "dry electric night air",
      "steam venting from grates",
      "light fog blurring distant signs",
      "overcast with low neon ceiling",
    ],
    details: [
      "rain streaking vertically",
      "holographic ads flickering",
      "chrome reflections on wet ground",
      "glitch artifacts in signage",
      "vending machines glowing",
      "stacked crates and cables",
      "distant elevated rail",
      "puddles mirroring neon",
    ],
    style: [
      "2D anime synthwave cinematic background",
      "retrowave anime environment illustration",
      "CoMix Wave Films neon atmosphere art",
      "premium cyberpunk anime background 2D",
      "lofi neon anime background art",
    ],
    ratios: ["16:9", "2:3", "9:16"],
    neg: "photorealistic, 3D render, CGI, characters in foreground, blurry, low quality, watermark, text, logo, signature, drop shadows, flat lighting, ground plane, oversaturated candy colors, muddy, noisy",
    etsyKeywords: [
      "neon city poster",
      "synthwave art print",
      "retrowave wall art",
      "cyberpunk room decor",
      "neon anime poster",
      "music room wall art",
      "nightlife art print",
      "neon skyline decor",
      "DJ room art",
      "anime city print",
    ],
    etsyTitleBase: [
      "Neon City Night",
      "Retrowave Street",
      "Synthwave Cityscape",
      "Cyberpunk Alley",
      "Neon Rain District",
    ],
    rbKeywords: [
      "neon city",
      "retrowave",
      "cyberpunk",
      "neon street",
      "synthwave city",
      "rainy neon",
      "DJ vibes",
      "nightlife art",
    ],
    rbProducts: [
      "poster",
      "art print",
      "sticker",
      "phone case",
      "laptop sleeve",
      "notebook",
      "pin",
    ],
  },
  "Fantasy Tech": {
    tag: "FANTASY TECH",
    color: "#34d399",
    dim: "#031a10",
    glow: "0 0 40px rgba(52,211,153,0.2)",
    environments: [
      "orbital space station observation deck",
      "biopunk research lab interior",
      "alien megacity terrace",
      "deep space observatory window",
      "underwater research facility",
      "ancient-tech ruins",
      "floating island platform",
      "arcane control room with rune interfaces",
    ],
    moods: [
      "vast cosmic wonder",
      "quiet scientific discovery",
      "solarpunk optimism",
      "deep space isolation",
      "future nostalgia",
      "technological awe",
    ],
    lighting: [
      "bioluminescent blue-green ambient",
      "solar panel refraction glow",
      "holographic UI panel light",
      "deep space starfield backlight",
      "plasma arc fill light",
      "crystalline prismatic scatter",
    ],
    weather: [
      "zero atmosphere exterior",
      "alien storm beyond glass",
      "nebula glow through viewport",
      "still pressurized interior",
      "auroral energy field outside",
      "soft ionized air glow",
    ],
    details: [
      "floating data streams",
      "alien flora in specimen tanks",
      "distant ringed planet visible",
      "mechanical fauna idle",
      "energy conduits pulsing",
      "ancient glyphs on tech panels",
      "star charts projected",
      "levitating instruments",
    ],
    style: [
      "2D anime sci-fi cinematic background",
      "premium anime fantasy-tech environment art",
      "CoMix Wave Films atmospheric space illustration",
      "Korean webtoon sci-fi background",
      "Makoto Shinkai-influenced cosmic 2D environment",
    ],
    ratios: ["16:9", "2:3", "1:1"],
    neg: "photorealistic, 3D render, CGI, characters in foreground, blurry, low quality, watermark, text, logo, signature, drop shadows, flat lighting, ground plane, generic space clip art, muddy, noisy, oversaturated",
    etsyKeywords: [
      "sci-fi wall art",
      "space room decor",
      "fantasy tech poster",
      "anime space print",
      "futuristic wall art",
      "cosmic room decor",
      "sci-fi art print",
      "space station poster",
      "biopunk art",
      "fantasy room decor",
    ],
    etsyTitleBase: [
      "Cosmic Observatory",
      "Arcane Tech Lab",
      "Space Station Lookout",
      "Biopunk Research Bay",
      "Orbital Platform",
    ],
    rbKeywords: [
      "sci-fi art",
      "space station",
      "biopunk",
      "cosmic art",
      "fantasy tech",
      "arcane lab",
      "alien world",
      "futuristic",
    ],
    rbProducts: [
      "poster",
      "art print",
      "sticker",
      "phone case",
      "notebook",
      "tapestry",
      "canvas print",
    ],
  },
  SynthWave: {
    tag: "SYNTHWAVE",
    color: "#f472b6",
    dim: "#2a0a1a",
    glow: "0 0 40px rgba(244,114,182,0.25)",
    environments: [
      "retrowave chrome highway at sunset",
      "outrun grid landscape at dusk",
      "retro arcade cabinet room",
      "VHS-era drive-in theatre",
      "80s rooftop pool overlooking skyline",
      "cassette deck studio interior",
      "neon desert road with distant mountains",
      "chrome cityscape with floating geometric shapes",
    ],
    moods: [
      "pure retrowave euphoria",
      "nostalgic 80s longing",
      "neon-soaked dreamlike calm",
      "outrun adrenaline energy",
      "VHS-haze warmth",
      "chrome-and-pink reverie",
    ],
    lighting: [
      "hot pink and deep purple horizon split",
      "chrome reflection sunburst",
      "scanline-filtered warm glow",
      "retrowave magenta-to-teal gradient sky",
      "CRT-glow amber warmth",
      "sun grid lens flare",
    ],
    weather: [
      "clear dry electric dusk",
      "thin cloud wisps catching the gradient",
      "perfectly still retrowave atmosphere",
      "hazy chromatic aberration air",
      "light interference shimmer",
      "crisp retro dry night",
    ],
    details: [
      "perspective grid receding to horizon",
      "palm trees silhouetted",
      "flying geometric shapes",
      "chrome sphere reflections",
      "VHS scan-line overlay feel",
      "cassette tapes scattered",
      "sun with horizontal line cuts",
      "checkerboard floor pattern",
    ],
    style: [
      "2D retrowave anime cinematic background",
      "outrun aesthetic anime illustration",
      "premium synthwave environment art 2D",
      "lofi retrowave background art",
      "CoMix Wave Films synthwave atmosphere",
    ],
    ratios: ["16:9", "4:5", "2:3", "1:1"],
    neg: "photorealistic, 3D render, CGI, characters in foreground, blurry, low quality, watermark, text, logo, signature, drop shadows, flat lighting, ground plane, muddy colors, modern aesthetic, realistic cars, noisy",
    etsyKeywords: [
      "synthwave wall art",
      "retrowave poster",
      "outrun art print",
      "80s retro wall art",
      "vaporwave print",
      "neon retro poster",
      "synthwave room decor",
      "retrowave digital download",
      "outrun aesthetic print",
      "retro neon art",
    ],
    etsyTitleBase: [
      "Retrowave Horizon",
      "Outrun Sunset",
      "SynthWave Grid",
      "Chrome Dusk Drive",
      "Retrowave Skyline",
    ],
    rbKeywords: [
      "synthwave",
      "retrowave",
      "outrun",
      "80s neon",
      "vaporwave",
      "chrome sunset",
      "retro grid",
      "neon horizon",
    ],
    rbProducts: [
      "poster",
      "art print",
      "sticker",
      "phone case",
      "laptop sleeve",
      "pin",
      "notebook",
    ],
  },
};

export const RATIO_INFO = {
  "16:9": {
    px: "1792 x 1024",
    w: 16,
    h: 9,
    use: "Desktop wallpaper | Etsy download | landscape poster",
  },
  "4:5": {
    px: "896 x 1120",
    w: 4,
    h: 5,
    use: "Instagram post | portrait print",
  },
  "2:3": {
    px: "768 x 1152",
    w: 2,
    h: 3,
    use: "11x14 | 16x20 print standard | tall poster",
  },
  "1:1": {
    px: "1024 x 1024",
    w: 1,
    h: 1,
    use: "Redbubble products | sticker | thumbnail",
  },
  "9:16": {
    px: "1080 x 1920",
    w: 9,
    h: 16,
    use: "Phone wallpaper | story format | vertical download",
  },
};

export const CHATGPT_SIZE = {
  "16:9": "1792x1024",
  "4:5": "1024x1792",
  "2:3": "1024x1792",
  "1:1": "1024x1024",
  "9:16": "1024x1792",
};

export const LANE_SUPPORT_POOLS = {
  "Setup Vibe": {
    viewpoints: [
      "over-the-shoulder",
      "eye-level street view",
      "medium distance with depth",
      "isometric perspective",
    ],
    palettes: [
      "cool teal and slate gray",
      "warm amber and deep brown",
      "muted sage and cream",
    ],
    compositions: [
      "frame within a frame",
      "layered depth planes",
      "centered symmetry",
      "rule of thirds",
    ],
    textures: [
      "brushed metal",
      "aged wood",
      "frosted glass",
      "matte concrete",
      "worn denim",
    ],
    depths: [
      "shallow focus with foreground blur",
      "soft bokeh background",
      "rack focus on midground",
      "medium depth of field",
    ],
    soundRefs: [
      "lo-fi hip hop beat",
      "deep house groove",
      "jazz piano late night",
      "ambient drone",
    ],
  },
  "Sunset Pulse": {
    viewpoints: [
      "wide establishing shot",
      "low angle looking up",
      "eye-level street view",
      "medium distance with depth",
    ],
    palettes: [
      "warm amber and deep brown",
      "soft peach and dusty rose",
      "warm terracotta and rust",
    ],
    compositions: [
      "leading lines to horizon",
      "rule of thirds",
      "diagonal flow left to right",
      "S-curve depth",
    ],
    textures: [
      "aged wood",
      "rough brick",
      "matte concrete",
      "soft velvet",
    ],
    depths: [
      "deep infinite focus",
      "medium depth of field",
      "soft bokeh background",
    ],
    soundRefs: [
      "ethereal vocal pad",
      "jazz piano late night",
      "Afrobeat rhythm",
      "ambient drone",
    ],
  },
  "Neon Deck": {
    viewpoints: [
      "low angle looking up",
      "dramatic worm's eye",
      "eye-level street view",
      "over-the-shoulder",
    ],
    palettes: [
      "neon magenta and deep black",
      "synthwave purple and cyan",
      "rich violet and gold",
    ],
    compositions: [
      "diagonal flow left to right",
      "layered depth planes",
      "frame within a frame",
      "asymmetric weight right",
    ],
    textures: [
      "wet chrome",
      "brushed metal",
      "translucent resin",
      "matte concrete",
    ],
    depths: [
      "soft bokeh background",
      "shallow focus with foreground blur",
      "rack focus on midground",
    ],
    soundRefs: [
      "synthwave electro pulse",
      "vaporwave tape hiss",
      "festival EDM drop",
      "city rain ambience",
    ],
  },
  "Fantasy Tech": {
    viewpoints: [
      "wide establishing shot",
      "bird's eye overhead",
      "isometric perspective",
      "medium distance with depth",
    ],
    palettes: [
      "cool teal and slate gray",
      "muted sage and cream",
      "earthy olive and bronze",
      "rich violet and gold",
    ],
    compositions: [
      "centered symmetry",
      "layered depth planes",
      "leading lines to horizon",
      "frame within a frame",
    ],
    textures: [
      "translucent resin",
      "frosted glass",
      "polished marble",
      "brushed metal",
    ],
    depths: [
      "deep infinite focus",
      "medium depth of field",
      "tack-sharp foreground",
    ],
    soundRefs: [
      "ambient drone",
      "ethereal vocal pad",
      "deep house groove",
    ],
  },
  SynthWave: {
    viewpoints: [
      "wide establishing shot",
      "low angle looking up",
      "dramatic worm's eye",
      "isometric perspective",
    ],
    palettes: [
      "synthwave purple and cyan",
      "neon magenta and deep black",
      "soft peach and dusty rose",
      "rich violet and gold",
    ],
    compositions: [
      "centered symmetry",
      "leading lines to horizon",
      "asymmetric weight right",
      "S-curve depth",
    ],
    textures: [
      "wet chrome",
      "translucent resin",
      "polished marble",
      "brushed metal",
    ],
    depths: [
      "deep infinite focus",
      "soft bokeh background",
      "medium depth of field",
    ],
    soundRefs: [
      "synthwave electro pulse",
      "vaporwave tape hiss",
      "festival EDM drop",
      "ethereal vocal pad",
    ],
  },
};

export const LANE_NAMES = Object.keys(LANES);

export const DEFAULT_NEG_TERMS = [
  "photorealistic",
  "3D render",
  "CGI",
  "characters in foreground",
  "blurry",
  "low quality",
  "watermark",
  "text",
  "logo",
  "signature",
  "drop shadows",
  "flat lighting",
  "ground plane",
  "oversaturated",
  "noisy",
  "muddy colors",
  "cluttered composition",
];
